version: "3.8"
services:
  mysql-db: # Nombre de contenedor MYSQL
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: cata2875
      MYSQL_DATABASE: bdbtingeso
    ports:
      - 33060:3306
  app:
    container_name: mysql-db-data
    image: katharoshxh/app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/bdbtingeso?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=cata2875
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db