spring:
  application:
    name: tingeso1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/bdbtingeso
    #username: root
    #password: cata2875
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}